import type { RealPackageItem, ChemicalPackage } from "@/types/content";

export const packagesContent = {
  hero: {
    title: "Pool Packages",
    subtitle:
      "Complete inground pool packages with everything included — steel walls, Hayward equipment, concrete footings, and lifetime transferrable warranties. Call for a free quote.",
  },

  packages: [
    {
      name: "Complete Package 14' x 28'",
      size: "14x28",
      price: null,
      poolSpecs: [
        "14' x 28' rectangle",
        "14 gauge steel walls",
        "Lifetime transferrable warranty",
        "Concrete footing (6 yards)",
        '6" sono tubes 4ft OC',
        '2x 18" skimmers',
        "2x Hayward bottom drains",
        "3 return fittings",
      ],
      equipment: [
        "8ft concrete walk-in steps",
        "Hayward SuperPump",
        "Hayward 250K BTU heater",
        "Hayward C-4000 filter",
        "3-step ladder",
        "Solar cover + reel",
        "3ft concrete deck",
        "Automatic pool cleaner",
        "Underwater light",
        "Accessory kit",
      ],
    },
    {
      name: "Complete Package 18' x 36'",
      size: "18x36",
      price: "$51,995",
      poolSpecs: [
        "18' x 36' rectangle",
        "14 gauge steel walls",
        "Lifetime transferrable warranty",
        "Concrete footing (6 yards)",
        '6" sono tubes 4ft OC',
        '2x 18" skimmers',
        '2x 8" bottom drains',
        "3 return fittings",
      ],
      equipment: [
        "1HP Hayward SuperPump",
        "Hayward 250K BTU heater",
        "Hayward C-4000 filter",
        "3-step ladder with rails",
        "Solar cover + reel",
        "8ft walk-in steps",
        "Underwater light",
        "Polaris robotic cleaner",
        "Accessory kit",
      ],
      additionalCosts: [
        "Permit: $300-600",
        "Gas line: $800-1,000",
        "Electrical: $2,700-3,000",
        "Fence: $28/LF",
      ],
    },
    {
      name: "Complete Package 18' x 36' (Premium Auto-Cover)",
      size: "18x36",
      price: null,
      poolSpecs: [
        "18' x 36' rectangle",
        "14 gauge steel walls",
        '1.5" Tiger Flex plumbing',
      ],
      equipment: [
        "1.5HP Hayward SuperPump",
        "Hayward 250K BTU heater",
        "Hayward C-4000 filter",
        "Colored LED light",
        "Latham 20mil/27mil liner",
        "2' wall ladder with rails",
        "9' corner steel step",
        "Coverstar Under Track Auto-Cover",
        '42" OC handrails',
        "Polaris robotic cleaner",
      ],
      additionalCosts: [
        "Permit: $300-600",
        "Gas line: $1,500",
        "Electrical: $4,000",
        "Dirt haul: $1,500",
        "Fence: $28/LF",
      ],
      bonuses: [
        "Free pool closing",
        "Educational instruction for first-time pool owners",
      ],
    },
    {
      name: "Complete Package 20' x 40'",
      size: "20x40",
      price: null,
      poolSpecs: [
        "20' x 40' rectangle",
        "14 gauge steel walls",
        '1.5" Tiger Flex plumbing',
        "Concrete footing (7 yards)",
        '2x 8" bottom drains',
      ],
      equipment: [
        "1.5HP Hayward SuperPump",
        "Hayward 250K BTU heater",
        "Hayward C-4000 filter",
        "Colored LED light",
        "Latham 20mil/27mil liner",
        "2' wall ladder with rails",
        "9' corner steel step",
        "Coverstar Under Track Auto-Cover",
        '42" OC handrails',
        "Polaris robotic cleaner",
      ],
      additionalCosts: [
        "Permit: $300-600",
        "Gas line: $1,500",
        "Electrical: $4,000",
        "Dirt haul: $1,500",
        "Fence: $18/LF",
      ],
    },
  ] satisfies RealPackageItem[],

  chemicalPackage: {
    name: "Chemical Start-Up Package",
    price: "$225",
    items: [
      "Super Sequest (metal control)",
      "Algaecide 30%",
      "8 lbs chlorinating granules",
      '25 lbs 3" chlorinating tabs',
    ],
    freeItems: [
      "7.5 lbs Alkalinity Up ($22 value)",
      "1 qt Sun Cover Cleaner ($20 value)",
    ],
  } satisfies ChemicalPackage,

  note: "All packages include professional installation by Paragon Pools. Owner Mike Henry is on-site for every project. Pricing depends on site conditions. Contact us for a personalized quote.",
};
